### ISSUE TITLE
Circuit crash

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#60] opened 2017-08-07 13:25 UTC
https://github.com/ZeroK-RTS/CrashReports/issues/1728

**Comment by rlcevg** [comment] 2017-08-11 10:35
#55  could be related: early crash (11-12th frame) on chicken map

**Comment by GoogleFrog** [comment] 2017-08-13 05:27
Here is a crash/hang at frame 11 for circuit https://github.com/ZeroK-RTS/CrashReports/issues/1771.

**Comment by GoogleFrog** [comment] 2017-08-16 00:27
https://github.com/ZeroK-RTS/CrashReports/issues/1800

**Comment by rlcevg** [comment] 2017-08-16 22:10
ZeroK-RTS/CrashReports#1800 - reproducible by map DuelRift 1.0: ai doesn't know what to do with units that has no passable areas; fixing.

Yet couldn't figure how to reproduce chicken's crash (11-12 frame)

**Comment by GoogleFrog** [comment] 2017-08-17 03:58
Global LOS crash https://github.com/ZeroK-RTS/CrashReports/issues/1812

**Comment by rlcevg** [comment] 2017-08-17 14:18
ZeroK-RTS/CrashReports#1812 - globalLOS indeed, fixed by https://github.com/rlcevg/CircuitAI/commit/257c056b9b7bc88d9aab1e9a0169576c31b476b9

**Comment by rlcevg** [comment] 2017-08-17 17:00
ZeroK-RTS/CrashReports#1800 - fixed by https://github.com/rlcevg/CircuitAI/commit/4713adfe014f8a4652f5d69e60d9a6cee787f78f
The map is kinda buggy, can't join as spectator, needs atleast 1 player or it will go into infinite loop (with or without any AI).

**Comment by GoogleFrog** [comment] 2017-08-18 12:24
https://github.com/ZeroK-RTS/CrashReports/issues/1815

**Comment by rlcevg** [comment] 2017-08-19 23:29
Another chicken crash, wich is a bit strange due to the nature of the cause: data sharing between AIs (map doesn't matter). Merging 1st AI (which is a rare uncommon case) that is responsible for initialization of shared data breaks some stuff. Fix: delegate authority to another valid AI.

**Comment by rlcevg** [comment] 2017-08-20 13:40
https://github.com/rlcevg/CircuitAI/commit/ce173e3ea505e20934710c3e43d00d08620c6749

**Closed by rlcevg** 2017-08-20 13:40 UTC
